### ISSUE TITLE
Required Link headers missing on content distribution requests

### ISSUE THREAD

**Issue by johnspurlock** [clone1018/WebSubHub#1]
Hi there - thanks for https://websubhub.com/

One thing I noticed is that your content distribution requests are missing the required Link http headers.

You can either add two Link headers:
e.g.
```
Link: <http://topic/url>; rel=self
Link: <https://websubhub.com/hub>; rel=hub
```

Or a single one with multiple values (like google's hub does, and is the preferred way according to the spec)
e.g.
```
Link: <http://topic/url>; rel=self, <https://websubhub.com/hub>; rel=hub
```

From the spec: https://www.w3.org/TR/websub/#x7-content-distribution

> The request MUST include at least one Link Header [[RFC5988](https://www.w3.org/TR/websub/#bib-RFC5988)] with rel=hub pointing to a Hub associated with the topic being updated. It MUST also include one Link Header [[RFC5988](https://www.w3.org/TR/websub/#bib-RFC5988)] with rel=self set to the canonical URL of the topic being updated. The Hub SHOULD combine these headers into a single Link Header [[RFC5988](https://www.w3.org/TR/websub/#bib-RFC5988)]. All these URLs are those resulting from the discovery process ([Section 3](https://www.w3.org/TR/websub/#discovery)). The subscriber MUST NOT use these Link headers to identify the subscription corresponding to the content distribution request, because the Link headers are metadata associated with the topic content, not with any particular subscription. For example, the topic URL in the content distribution request may be different from the topic URL that was originally subscribed to.

**Comment by clone1018** [comment]
Hey there! Thanks for letting me know, I can probably get this in sometime this week. Will keep you updated!
