### ISSUE TITLE
Support JSON?

### ISSUE THREAD

**Issue by dmathewwws** [clone1018/WebSubHub#3]
Hi,

I was curious if WebSubHub could be used to notify about changes to any resource (ex: JSON). I have public JSON "feeds" and would like to use WebSub to notify any subscriber that something in that JSON has changed.

**Comment by clone1018** [comment]
Hey @dmathewwws. The good news is I think that it's already supported. You should be able to use any content type, including JSON. It works when I try it via https://websub.rocks/hub/106 -- let me know if this is what you are trying to do!

**Comment by dmathewwws** [comment]
Yup! Thats it. Thanks :)

I'm a couple months away, but im working on a comic app, but its going to be powered by open standard JSON feeds (similar to how podcasts are powered by RSS) and was looking for a WebSub hub to use.
